import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/nav_bar";
import Footer from "@/components/footer";
import { UserProvider } from "@/contexts/user_context";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${inter.className} flex min-h-screen flex-col`}>
          <NavBar />
          <main className="mt-[96Px] flex-grow">{children}</main>
          <Footer />
          <Toaster className="bg-red-500" />
        </body>
      </UserProvider>
    </html>
  );
}
